# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/arnito/ClionProjects/genland

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/arnito/ClionProjects/genland

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arnito/ClionProjects/genland/CMakeFiles /home/arnito/ClionProjects/genland/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arnito/ClionProjects/genland/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named genland

# Build rule for target.
genland: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 genland
.PHONY : genland

# fast build rule for target.
genland/fast:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/build
.PHONY : genland/fast

AnimatedTile.o: AnimatedTile.cpp.o

.PHONY : AnimatedTile.o

# target to build an object file
AnimatedTile.cpp.o:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/AnimatedTile.cpp.o
.PHONY : AnimatedTile.cpp.o

AnimatedTile.i: AnimatedTile.cpp.i

.PHONY : AnimatedTile.i

# target to preprocess a source file
AnimatedTile.cpp.i:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/AnimatedTile.cpp.i
.PHONY : AnimatedTile.cpp.i

AnimatedTile.s: AnimatedTile.cpp.s

.PHONY : AnimatedTile.s

# target to generate assembly for a file
AnimatedTile.cpp.s:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/AnimatedTile.cpp.s
.PHONY : AnimatedTile.cpp.s

Background.o: Background.cpp.o

.PHONY : Background.o

# target to build an object file
Background.cpp.o:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Background.cpp.o
.PHONY : Background.cpp.o

Background.i: Background.cpp.i

.PHONY : Background.i

# target to preprocess a source file
Background.cpp.i:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Background.cpp.i
.PHONY : Background.cpp.i

Background.s: Background.cpp.s

.PHONY : Background.s

# target to generate assembly for a file
Background.cpp.s:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Background.cpp.s
.PHONY : Background.cpp.s

Button.o: Button.cpp.o

.PHONY : Button.o

# target to build an object file
Button.cpp.o:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Button.cpp.o
.PHONY : Button.cpp.o

Button.i: Button.cpp.i

.PHONY : Button.i

# target to preprocess a source file
Button.cpp.i:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Button.cpp.i
.PHONY : Button.cpp.i

Button.s: Button.cpp.s

.PHONY : Button.s

# target to generate assembly for a file
Button.cpp.s:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Button.cpp.s
.PHONY : Button.cpp.s

Chunk.o: Chunk.cpp.o

.PHONY : Chunk.o

# target to build an object file
Chunk.cpp.o:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Chunk.cpp.o
.PHONY : Chunk.cpp.o

Chunk.i: Chunk.cpp.i

.PHONY : Chunk.i

# target to preprocess a source file
Chunk.cpp.i:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Chunk.cpp.i
.PHONY : Chunk.cpp.i

Chunk.s: Chunk.cpp.s

.PHONY : Chunk.s

# target to generate assembly for a file
Chunk.cpp.s:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Chunk.cpp.s
.PHONY : Chunk.cpp.s

Clock.o: Clock.cpp.o

.PHONY : Clock.o

# target to build an object file
Clock.cpp.o:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Clock.cpp.o
.PHONY : Clock.cpp.o

Clock.i: Clock.cpp.i

.PHONY : Clock.i

# target to preprocess a source file
Clock.cpp.i:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Clock.cpp.i
.PHONY : Clock.cpp.i

Clock.s: Clock.cpp.s

.PHONY : Clock.s

# target to generate assembly for a file
Clock.cpp.s:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Clock.cpp.s
.PHONY : Clock.cpp.s

Drawer.o: Drawer.cpp.o

.PHONY : Drawer.o

# target to build an object file
Drawer.cpp.o:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Drawer.cpp.o
.PHONY : Drawer.cpp.o

Drawer.i: Drawer.cpp.i

.PHONY : Drawer.i

# target to preprocess a source file
Drawer.cpp.i:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Drawer.cpp.i
.PHONY : Drawer.cpp.i

Drawer.s: Drawer.cpp.s

.PHONY : Drawer.s

# target to generate assembly for a file
Drawer.cpp.s:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Drawer.cpp.s
.PHONY : Drawer.cpp.s

Game.o: Game.cpp.o

.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i

.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s

.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Game.cpp.s
.PHONY : Game.cpp.s

Inputs.o: Inputs.cpp.o

.PHONY : Inputs.o

# target to build an object file
Inputs.cpp.o:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Inputs.cpp.o
.PHONY : Inputs.cpp.o

Inputs.i: Inputs.cpp.i

.PHONY : Inputs.i

# target to preprocess a source file
Inputs.cpp.i:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Inputs.cpp.i
.PHONY : Inputs.cpp.i

Inputs.s: Inputs.cpp.s

.PHONY : Inputs.s

# target to generate assembly for a file
Inputs.cpp.s:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Inputs.cpp.s
.PHONY : Inputs.cpp.s

Inventory.o: Inventory.cpp.o

.PHONY : Inventory.o

# target to build an object file
Inventory.cpp.o:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Inventory.cpp.o
.PHONY : Inventory.cpp.o

Inventory.i: Inventory.cpp.i

.PHONY : Inventory.i

# target to preprocess a source file
Inventory.cpp.i:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Inventory.cpp.i
.PHONY : Inventory.cpp.i

Inventory.s: Inventory.cpp.s

.PHONY : Inventory.s

# target to generate assembly for a file
Inventory.cpp.s:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Inventory.cpp.s
.PHONY : Inventory.cpp.s

Item.o: Item.cpp.o

.PHONY : Item.o

# target to build an object file
Item.cpp.o:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Item.cpp.o
.PHONY : Item.cpp.o

Item.i: Item.cpp.i

.PHONY : Item.i

# target to preprocess a source file
Item.cpp.i:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Item.cpp.i
.PHONY : Item.cpp.i

Item.s: Item.cpp.s

.PHONY : Item.s

# target to generate assembly for a file
Item.cpp.s:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Item.cpp.s
.PHONY : Item.cpp.s

Light.o: Light.cpp.o

.PHONY : Light.o

# target to build an object file
Light.cpp.o:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Light.cpp.o
.PHONY : Light.cpp.o

Light.i: Light.cpp.i

.PHONY : Light.i

# target to preprocess a source file
Light.cpp.i:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Light.cpp.i
.PHONY : Light.cpp.i

Light.s: Light.cpp.s

.PHONY : Light.s

# target to generate assembly for a file
Light.cpp.s:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Light.cpp.s
.PHONY : Light.cpp.s

Main.o: Main.cpp.o

.PHONY : Main.o

# target to build an object file
Main.cpp.o:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Main.cpp.o
.PHONY : Main.cpp.o

Main.i: Main.cpp.i

.PHONY : Main.i

# target to preprocess a source file
Main.cpp.i:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Main.cpp.i
.PHONY : Main.cpp.i

Main.s: Main.cpp.s

.PHONY : Main.s

# target to generate assembly for a file
Main.cpp.s:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Main.cpp.s
.PHONY : Main.cpp.s

Map.o: Map.cpp.o

.PHONY : Map.o

# target to build an object file
Map.cpp.o:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Map.cpp.o
.PHONY : Map.cpp.o

Map.i: Map.cpp.i

.PHONY : Map.i

# target to preprocess a source file
Map.cpp.i:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Map.cpp.i
.PHONY : Map.cpp.i

Map.s: Map.cpp.s

.PHONY : Map.s

# target to generate assembly for a file
Map.cpp.s:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Map.cpp.s
.PHONY : Map.cpp.s

MenuConfigGame.o: MenuConfigGame.cpp.o

.PHONY : MenuConfigGame.o

# target to build an object file
MenuConfigGame.cpp.o:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/MenuConfigGame.cpp.o
.PHONY : MenuConfigGame.cpp.o

MenuConfigGame.i: MenuConfigGame.cpp.i

.PHONY : MenuConfigGame.i

# target to preprocess a source file
MenuConfigGame.cpp.i:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/MenuConfigGame.cpp.i
.PHONY : MenuConfigGame.cpp.i

MenuConfigGame.s: MenuConfigGame.cpp.s

.PHONY : MenuConfigGame.s

# target to generate assembly for a file
MenuConfigGame.cpp.s:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/MenuConfigGame.cpp.s
.PHONY : MenuConfigGame.cpp.s

MenuLoadGame.o: MenuLoadGame.cpp.o

.PHONY : MenuLoadGame.o

# target to build an object file
MenuLoadGame.cpp.o:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/MenuLoadGame.cpp.o
.PHONY : MenuLoadGame.cpp.o

MenuLoadGame.i: MenuLoadGame.cpp.i

.PHONY : MenuLoadGame.i

# target to preprocess a source file
MenuLoadGame.cpp.i:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/MenuLoadGame.cpp.i
.PHONY : MenuLoadGame.cpp.i

MenuLoadGame.s: MenuLoadGame.cpp.s

.PHONY : MenuLoadGame.s

# target to generate assembly for a file
MenuLoadGame.cpp.s:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/MenuLoadGame.cpp.s
.PHONY : MenuLoadGame.cpp.s

MenuMain.o: MenuMain.cpp.o

.PHONY : MenuMain.o

# target to build an object file
MenuMain.cpp.o:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/MenuMain.cpp.o
.PHONY : MenuMain.cpp.o

MenuMain.i: MenuMain.cpp.i

.PHONY : MenuMain.i

# target to preprocess a source file
MenuMain.cpp.i:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/MenuMain.cpp.i
.PHONY : MenuMain.cpp.i

MenuMain.s: MenuMain.cpp.s

.PHONY : MenuMain.s

# target to generate assembly for a file
MenuMain.cpp.s:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/MenuMain.cpp.s
.PHONY : MenuMain.cpp.s

NewGameMenu.o: NewGameMenu.cpp.o

.PHONY : NewGameMenu.o

# target to build an object file
NewGameMenu.cpp.o:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/NewGameMenu.cpp.o
.PHONY : NewGameMenu.cpp.o

NewGameMenu.i: NewGameMenu.cpp.i

.PHONY : NewGameMenu.i

# target to preprocess a source file
NewGameMenu.cpp.i:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/NewGameMenu.cpp.i
.PHONY : NewGameMenu.cpp.i

NewGameMenu.s: NewGameMenu.cpp.s

.PHONY : NewGameMenu.s

# target to generate assembly for a file
NewGameMenu.cpp.s:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/NewGameMenu.cpp.s
.PHONY : NewGameMenu.cpp.s

Player.o: Player.cpp.o

.PHONY : Player.o

# target to build an object file
Player.cpp.o:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Player.cpp.o
.PHONY : Player.cpp.o

Player.i: Player.cpp.i

.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s

.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Player.cpp.s
.PHONY : Player.cpp.s

RunningGame.o: RunningGame.cpp.o

.PHONY : RunningGame.o

# target to build an object file
RunningGame.cpp.o:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/RunningGame.cpp.o
.PHONY : RunningGame.cpp.o

RunningGame.i: RunningGame.cpp.i

.PHONY : RunningGame.i

# target to preprocess a source file
RunningGame.cpp.i:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/RunningGame.cpp.i
.PHONY : RunningGame.cpp.i

RunningGame.s: RunningGame.cpp.s

.PHONY : RunningGame.s

# target to generate assembly for a file
RunningGame.cpp.s:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/RunningGame.cpp.s
.PHONY : RunningGame.cpp.s

Simplex2d.o: Simplex2d.cpp.o

.PHONY : Simplex2d.o

# target to build an object file
Simplex2d.cpp.o:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Simplex2d.cpp.o
.PHONY : Simplex2d.cpp.o

Simplex2d.i: Simplex2d.cpp.i

.PHONY : Simplex2d.i

# target to preprocess a source file
Simplex2d.cpp.i:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Simplex2d.cpp.i
.PHONY : Simplex2d.cpp.i

Simplex2d.s: Simplex2d.cpp.s

.PHONY : Simplex2d.s

# target to generate assembly for a file
Simplex2d.cpp.s:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Simplex2d.cpp.s
.PHONY : Simplex2d.cpp.s

Sun.o: Sun.cpp.o

.PHONY : Sun.o

# target to build an object file
Sun.cpp.o:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Sun.cpp.o
.PHONY : Sun.cpp.o

Sun.i: Sun.cpp.i

.PHONY : Sun.i

# target to preprocess a source file
Sun.cpp.i:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Sun.cpp.i
.PHONY : Sun.cpp.i

Sun.s: Sun.cpp.s

.PHONY : Sun.s

# target to generate assembly for a file
Sun.cpp.s:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Sun.cpp.s
.PHONY : Sun.cpp.s

TextureManager.o: TextureManager.cpp.o

.PHONY : TextureManager.o

# target to build an object file
TextureManager.cpp.o:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/TextureManager.cpp.o
.PHONY : TextureManager.cpp.o

TextureManager.i: TextureManager.cpp.i

.PHONY : TextureManager.i

# target to preprocess a source file
TextureManager.cpp.i:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/TextureManager.cpp.i
.PHONY : TextureManager.cpp.i

TextureManager.s: TextureManager.cpp.s

.PHONY : TextureManager.s

# target to generate assembly for a file
TextureManager.cpp.s:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/TextureManager.cpp.s
.PHONY : TextureManager.cpp.s

Tile.o: Tile.cpp.o

.PHONY : Tile.o

# target to build an object file
Tile.cpp.o:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Tile.cpp.o
.PHONY : Tile.cpp.o

Tile.i: Tile.cpp.i

.PHONY : Tile.i

# target to preprocess a source file
Tile.cpp.i:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Tile.cpp.i
.PHONY : Tile.cpp.i

Tile.s: Tile.cpp.s

.PHONY : Tile.s

# target to generate assembly for a file
Tile.cpp.s:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/Tile.cpp.s
.PHONY : Tile.cpp.s

WorldBackground.o: WorldBackground.cpp.o

.PHONY : WorldBackground.o

# target to build an object file
WorldBackground.cpp.o:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/WorldBackground.cpp.o
.PHONY : WorldBackground.cpp.o

WorldBackground.i: WorldBackground.cpp.i

.PHONY : WorldBackground.i

# target to preprocess a source file
WorldBackground.cpp.i:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/WorldBackground.cpp.i
.PHONY : WorldBackground.cpp.i

WorldBackground.s: WorldBackground.cpp.s

.PHONY : WorldBackground.s

# target to generate assembly for a file
WorldBackground.cpp.s:
	$(MAKE) -f CMakeFiles/genland.dir/build.make CMakeFiles/genland.dir/WorldBackground.cpp.s
.PHONY : WorldBackground.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... genland"
	@echo "... AnimatedTile.o"
	@echo "... AnimatedTile.i"
	@echo "... AnimatedTile.s"
	@echo "... Background.o"
	@echo "... Background.i"
	@echo "... Background.s"
	@echo "... Button.o"
	@echo "... Button.i"
	@echo "... Button.s"
	@echo "... Chunk.o"
	@echo "... Chunk.i"
	@echo "... Chunk.s"
	@echo "... Clock.o"
	@echo "... Clock.i"
	@echo "... Clock.s"
	@echo "... Drawer.o"
	@echo "... Drawer.i"
	@echo "... Drawer.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... Inputs.o"
	@echo "... Inputs.i"
	@echo "... Inputs.s"
	@echo "... Inventory.o"
	@echo "... Inventory.i"
	@echo "... Inventory.s"
	@echo "... Item.o"
	@echo "... Item.i"
	@echo "... Item.s"
	@echo "... Light.o"
	@echo "... Light.i"
	@echo "... Light.s"
	@echo "... Main.o"
	@echo "... Main.i"
	@echo "... Main.s"
	@echo "... Map.o"
	@echo "... Map.i"
	@echo "... Map.s"
	@echo "... MenuConfigGame.o"
	@echo "... MenuConfigGame.i"
	@echo "... MenuConfigGame.s"
	@echo "... MenuLoadGame.o"
	@echo "... MenuLoadGame.i"
	@echo "... MenuLoadGame.s"
	@echo "... MenuMain.o"
	@echo "... MenuMain.i"
	@echo "... MenuMain.s"
	@echo "... NewGameMenu.o"
	@echo "... NewGameMenu.i"
	@echo "... NewGameMenu.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... RunningGame.o"
	@echo "... RunningGame.i"
	@echo "... RunningGame.s"
	@echo "... Simplex2d.o"
	@echo "... Simplex2d.i"
	@echo "... Simplex2d.s"
	@echo "... Sun.o"
	@echo "... Sun.i"
	@echo "... Sun.s"
	@echo "... TextureManager.o"
	@echo "... TextureManager.i"
	@echo "... TextureManager.s"
	@echo "... Tile.o"
	@echo "... Tile.i"
	@echo "... Tile.s"
	@echo "... WorldBackground.o"
	@echo "... WorldBackground.i"
	@echo "... WorldBackground.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

